### ISSUE TITLE
Allow dynamic registration of instances

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-control-center#137]
When using the static profile, it can be annoying to always have to set the appropriate control center property to make a new service visible.

```
spring:
  cloud:
    discovery:
      client:
        simple:
           instances:
             service1:
             - uri: http://localhost:8080 
```

The idea would be to add a new API endpoint and button on the instance view page to dynamically add service instances.

The endpoint would take 2 inputs:
- service name (eg. "service1")
- instance URL (eg. "http://localhost:808O", "https://example.com")

The UI would consist of a "Register a new instance" button which would display a popup modal.
Behind the scenes, the API would add a spring cloud gateway route to the new instance.

Note: obviously those dynamically added services would be lost on control center restarts.
